MAX_RETRY_COUNT = 2
CRITIC_SCORE_THRESHOLD = 7.0
LLM_PROVIDER_ORDER = ["groq", "gemini", "openai"]
MAX_CONTENT_LENGTH = 5000
DEFAULT_PLATFORM = "LinkedIn"
DEFAULT_TONE = "Professional"
DEFAULT_STYLE = "Concise"
